# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Development Build

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hugo-version:
          - 'latest'
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ matrix.hugo-version }}
          extended: true

      - name: Run Hugo
        working-directory: sample-book
        run: hugo --themesDir ../..
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.4.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_PAGES_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./sample-book/public