# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Development Build

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hugo-version:
          - 'latest'
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ matrix.hugo-version }}
          extended: true

      - name: Run Hugo
        working-directory: sample-book
        run: hugo --themesDir ../..
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./sample-book/public # The folder the action should deploy.